const columns = [
    { name: "NAME", uid: "name" },
    { name: "ROLE", uid: "role" },
    { name: "STATUS", uid: "status" },
    { name: "ACTIONS", uid: "actions" },
  ];
  
  const users = [
    {
      id: 1,
      name: "Sophia Brown",
      role: "Product Manager",
      team: "Management",
      status: "active",
      age: "30",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026001b",
      email: "sophia.brown@example.com",
    },
    {
      id: 2,
      name: "Liam Garcia",
      role: "UX Designer",
      team: "Design",
      status: "paused",
      age: "26",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026702b",
      email: "liam.garcia@example.com",
    },
    {
      id: 3,
      name: "Emma Johnson",
      role: "QA Engineer",
      team: "Testing",
      status: "active",
      age: "27",
      avatar: "https://i.pravatar.cc/150?u=a04258114e29026704b",
      email: "emma.johnson@example.com",
    },
    {
      id: 4,
      name: "Noah Martinez",
      role: "Marketing Specialist",
      team: "Marketing",
      status: "vacation",
      age: "29",
      avatar: "https://i.pravatar.cc/150?u=a048581f4e29026707b",
      email: "noah.martinez@example.com",
    },
    {
      id: 5,
      name: "Olivia Davis",
      role: "Business Analyst",
      team: "Finance",
      status: "active",
      age: "31",
      avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026709b",
      email: "olivia.davis@example.com",
    },
    {
      id: 6,
      name: "Ethan Taylor",
      role: "Software Engineer",
      team: "Development",
      status: "paused",
      age: "23",
      avatar: "https://i.pravatar.cc/150?u=a012581f4e29026014b",
      email: "ethan.taylor@example.com",
    },
    {
      id: 7,
      name: "Mia Thomas",
      role: "HR Manager",
      team: "Human Resources",
      status: "active",
      age: "33",
      avatar: "https://i.pravatar.cc/150?u=a092581f4e29026029b",
      email: "mia.thomas@example.com",
    },
    {
      id: 8,
      name: "Lucas Anderson",
      role: "DevOps Engineer",
      team: "Operations",
      status: "vacation",
      age: "28",
      avatar: "https://i.pravatar.cc/150?u=a052581f4e29026034b",
      email: "lucas.anderson@example.com",
    },
    {
      id: 9,
      name: "Ava Wilson",
      role: "Data Scientist",
      team: "Analytics",
      status: "active",
      age: "25",
      avatar: "https://i.pravatar.cc/150?u=a092581f4e29026012b",
      email: "ava.wilson@example.com",
    },
    {
      id: 10,
      name: "Benjamin White",
      role: "Sales Representative",
      team: "Sales",
      status: "paused",
      age: "24",
      avatar: "https://i.pravatar.cc/150?u=a032581f4e29026045b",
      email: "benjamin.white@example.com",
    },
    {
      id: 11,
      name: "Isabella Moore",
      role: "Graphic Designer",
      team: "Design",
      status: "active",
      age: "27",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026016b",
      email: "isabella.moore@example.com",
    },
    {
      id: 12,
      name: "James Lee",
      role: "Technical Support",
      team: "Support",
      status: "vacation",
      age: "26",
      avatar: "https://i.pravatar.cc/150?u=a032581f4e29026009b",
      email: "james.lee@example.com",
    },
    {
      id: 13,
      name: "Charlotte Clark",
      role: "Social Media Manager",
      team: "Marketing",
      status: "active",
      age: "24",
      avatar: "https://i.pravatar.cc/150?u=a012581f4e29026020b",
      email: "charlotte.clark@example.com",
    },
    {
      id: 14,
      name: "Henry Turner",
      role: "System Administrator",
      team: "IT",
      status: "paused",
      age: "29",
      avatar: "https://i.pravatar.cc/150?u=a052581f4e29026024b",
      email: "henry.turner@example.com",
    },
    {
      id: 15,
      name: "Amelia Wright",
      role: "Content Writer",
      team: "Editorial",
      status: "active",
      age: "22",
      avatar: "https://i.pravatar.cc/150?u=a042581f4e29026037b",
      email: "amelia.wright@example.com",
    },
    {
      id: 16,
      name: "Elijah Scott",
      role: "IT Specialist",
      team: "Support",
      status: "active",
      age: "31",
      avatar: "https://i.pravatar.cc/150?u=a052581f4e29026039b",
      email: "elijah.scott@example.com",
    },
    {
      id: 17,
      name: "Harper King",
      role: "Operations Manager",
      team: "Operations",
      status: "paused",
      age: "34",
      avatar: "https://i.pravatar.cc/150?u=a012581f4e29026038b",
      email: "harper.king@example.com",
    },
    {
      id: 18,
      name: "Jack Baker",
      role: "Database Administrator",
      team: "IT",
      status: "active",
      age: "29",
      avatar: "https://i.pravatar.cc/150?u=a092581f4e29026017b",
      email: "jack.baker@example.com",
    },
    {
      id: 19,
      name: "Ella Carter",
      role: "SEO Analyst",
      team: "Marketing",
      status: "active",
      age: "28",
      avatar: "https://i.pravatar.cc/150?u=a082581f4e29026040b",
      email: "ella.carter@example.com",
    },
    {
      id: 20,
      name: "Daniel Harris",
      role: "Cloud Engineer",
      team: "Development",
      status: "vacation",
      age: "26",
      avatar: "https://i.pravatar.cc/150?u=a012581f4e29026021b",
      email: "daniel.harris@example.com",
    },
  ];
  
  export { columns, users };